<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PropuestaTecnica.Common\PropuestaTecnica.Common.csproj" />
    <ProjectReference Include="..\PropuestaTecnica.DataAccess\PropuestaTecnica.DataAccess.csproj" />
  </ItemGroup>

</Project>
